# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='critical_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='warning_days',
            field=models.IntegerField(default=2),
        ),
    ]
