# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0002_auto_20160714_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('limit_employees', models.IntegerField(default=2)),
                ('notifications', models.BooleanField(default=False)),
            ],
        ),
    ]
