# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0004_accounttype_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='limit_employees',
            field=models.IntegerField(default=5),
        ),
    ]
