# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0005_auto_20160715_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
