# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0006_auto_20160718_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
