# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0007_employee_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmodel',
            old_name='document_model_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='name',
        ),
    ]
