# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0008_auto_20160719_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='documentmodels',
            field=models.ManyToManyField(to='cerbereapp.DocumentModel'),
        ),
    ]
