# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0009_auto_20160721_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='documentmodels',
            new_name='documentmodels_list',
        ),
    ]
