# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0010_auto_20160721_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentmodel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerbereapp.DocumentModel')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerbereapp.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='employee_id',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
