# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0011_auto_20160724_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualdocument',
            old_name='documentmodel_id',
            new_name='documentmodel',
        ),
        migrations.RenameField(
            model_name='actualdocument',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
