# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0012_auto_20160724_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='documentmodels_list',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='cerbereapp.DocumentModel'),
        ),
    ]
