# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0013_auto_20160801_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualdocument',
            name='document_file',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='actualdocument',
            name='expiration_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='documentmodels_list',
            field=models.ManyToManyField(blank=True, default=None, to='cerbereapp.DocumentModel'),
        ),
    ]
