# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0014_auto_20160801_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualdocument',
            name='document_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
