# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerbereapp', '0003_auto_20160517_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
